name: psw
description: CLI client that downloads PSW order JSON.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  args: ^2.7.0
  http: ^1.2.2

dev_dependencies:
  lints: ^5.1.1
